BLACKLIST =  [
    ['remix', 'mix'],
    ['instrumental', 'piano', 'acoustic', 'acoustical', 'capella'],
    '[gmv]',
    'live',
    'cover',
    'coachella',
    'karaoke',
    'parody',
    'guitar',
    'tempe',
    'lil mazy',
    'tour',
    'event',
    'theatre',
    'show',
    'mashup',
    'sweden',
    'wwe',
    'Paris',
    'Worth Knight',
    'dallas house of blues',
    'chipmunks',
    'slide scene'
]
